platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: pal-tracker
  - name: version

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |

    export DEBIAN_FRONTEND="noninteractive"
    echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
    apt-get update
    
    deb [arch=amd64,i386] http://ftp.utexas.edu/mariadb/repo/10.1/debian jessie main
    deb [arch=amd64,i386] http://ftp.utexas.edu/mariadb/repo/10.1/debian jessie main
    deb-src http://ftp.utexas.edu/mariadb/repo/10.1/debian jessie main


    apt-get -y install python-software-properties
    apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
    apt-get -y  install software-properties-common
    apt-get -y install mariadb-server mariadb-client


    apt-get -y install mysql-server

    service mysql start

    cd pal-tracker
    mysql -uroot < databases/create_databases.sql
    chmod +x gradlew
    ./gradlew testMigrate clean build || (service mysql stop && exit 1)
    service mysql stop

    cp build/libs/pal-tracker-*.jar ../build-output
